### ISSUE TITLE
uninitialized constant RSpec::Matchers when running rake

### ISSUE THREAD

**Issue by mlomnicki** [RailsEventStore/rails_event_store#115]
Steps to reproduce

Gemfile:
```ruby
gem 'rails_event_store'

group :test do
   gem 'rspec-rails'
   gem 'rails_event_store-rspec'
end
```

```
RAILS_ENV=test rake db:create

rake aborted!
NameError: uninitialized constant RSpec::Matchers
/Users/michal/.rvm/gems/ruby-2.3.3/gems/rails_event_store-rspec-0.17.0/lib/rails_event_store/rspec/be_event.rb:115:in `<class:BeEvent>'
/Users/michal/.rvm/gems/ruby-2.3.3/gems/rails_event_store-rspec-0.17.0/lib/rails_event_store/rspec/be_event.rb:3:in `<module:RSpec>'
/Users/michal/.rvm/gems/ruby-2.3.3/gems/rails_event_store-rspec-0.17.0/lib/rails_event_store/rspec/be_event.rb:2:in `<module:RailsEventStore>'
/Users/michal/.rvm/gems/ruby-2.3.3/gems/rails_event_store-rspec-0.17.0/lib/rails_event_store/rspec/be_event.rb:1:in `<top (required)>'
/Users/michal/.rvm/gems/ruby-2.3.3/gems/rails_event_store-rspec-0.17.0/lib/rails_event_store/rspec.rb:8:in `<top (required)>'
```

or have a look at the sample app to reproduce the issue https://github.com/mlomnicki/res-rspec-error

The error goes away if I add 'rspec' to the Gemfile (rspec-rails is not enough)

```ruby
group :test do
   gem 'rspec'
   gem 'rspec-rails'
   gem 'rails_event_store-rspec'
end
```

**Comment by damireh** [comment]
Ive also encountered the same issue, I was able to work around it by adding `require: false` to my Gemfile

```ruby
group :test do
   gem 'rails_event_store-rspec', require: false
end
```

and explicitly requiring `require "rails_event_store/rspec"` in my `spec/rails_helper.rb`

```ruby
require "rails_event_store/rspec"

RSpec.configure do |config|
  config.include ::RailsEventStore::RSpec::Matchers
end
```

**Comment by fidel** [comment]
@mlomnicki @damireh could you please verify if [ad089b8](https://github.com/RailsEventStore/rails_event_store/commit/ad089b8d4d1333a78d5956429b7b2a3764fcc43c) works for you? I checked with https://github.com/mlomnicki/res-rspec-error and it seems to solve the issue.

**Comment by mlomnicki** [comment]
@fidel thanks for looking into it.

It looks like the issue still persists for me. The error is a bit different though.
```
 $ RAILS_ENV=test rake db:create
rake aborted!
NameError: uninitialized constant RSpec
/Users/michal/.rvm/gems/ruby-2.3.3/bundler/gems/rails_event_store-ad089b8d4d13/rails_event_store-rspec/lib/rails_event_store/rspec/be_event.rb:115:in `<class:BeEvent>'
/Users/michal/.rvm/gems/ruby-2.3.3/bundler/gems/rails_event_store-ad089b8d4d13/rails_event_store-rspec/lib/rails_event_store/rspec/be_event.rb:3:in `<module:RSpec>'
/Users/michal/.rvm/gems/ruby-2.3.3/bundler/gems/rails_event_store-ad089b8d4d13/rails_event_store-rspec/lib/rails_event_store/rspec/be_event.rb:2:in `<module:RailsEventStore>'
/Users/michal/.rvm/gems/ruby-2.3.3/bundler/gems/rails_event_store-ad089b8d4d13/rails_event_store-rspec/lib/rails_event_store/rspec/be_event.rb:1:in `<top (required)>'
/Users/michal/.rvm/gems/ruby-2.3.3/bundler/gems/rails_event_store-ad089b8d4d13/rails_event_store-rspec/lib/rails_event_store/rspec.rb:8:in `<top (required)>'
/Users/michal/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.4/lib/bundler/runtime.rb:96:in `require'
/Users/michal/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.4/lib/bundler/runtime.rb:96:in `rescue in block in require'
/Users/michal/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.4/lib/bundler/runtime.rb:73:in `block in require'
/Users/michal/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.4/lib/bundler/runtime.rb:66:in `each'
/Users/michal/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.4/lib/bundler/runtime.rb:66:in `require'
/Users/michal/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.4/lib/bundler.rb:108:in `require'
/Users/michal/projects/res-rspec-error/config/application.rb:7:in `<top (required)>'
/Users/michal/projects/res-rspec-error/Rakefile:4:in `require_relative'
/Users/michal/projects/res-rspec-error/Rakefile:4:in `<top (required)>'
LoadError: cannot load such file -- rails_event_store-rspec
/Users/michal/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.4/lib/bundler/runtime.rb:82:in `require'
/Users/michal/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.4/lib/bundler/runtime.rb:82:in `block (2 levels) in require'
/Users/michal/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.4/lib/bundler/runtime.rb:77:in `each'
/Users/michal/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.4/lib/bundler/runtime.rb:77:in `block in require'
/Users/michal/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.4/lib/bundler/runtime.rb:66:in `each'
/Users/michal/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.4/lib/bundler/runtime.rb:66:in `require'
/Users/michal/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.4/lib/bundler.rb:108:in `require'
/Users/michal/projects/res-rspec-error/config/application.rb:7:in `<top (required)>'
/Users/michal/projects/res-rspec-error/Rakefile:4:in `require_relative'
/Users/michal/projects/res-rspec-error/Rakefile:4:in `<top (required)>'
```

This happens with the sample app pointed to the master branch of RES https://github.com/mlomnicki/res-rspec-error/tree/git

**Comment by fidel** [comment]
Have you uninstalled the old rails_event_store-rspec first?

W dniu śr., 20.09.2017 o 16:31 Michał Łomnicki <notifications@github.com>
napisał(a):

**Comment by mlomnicki** [comment]
Uninstalled the old version but the problem remains. I can even reproduce it on Travis 
https://travis-ci.org/mlomnicki/res-rspec-error/builds/277826076

The exception points to this line https://github.com/RailsEventStore/rails_event_store/blob/ad089b8d4d1333a78d5956429b7b2a3764fcc43c/rails_event_store-rspec/lib/rails_event_store/rspec/be_event.rb#L115

Generally the error makes sense to me because RES-rspec doesn't `require 'rspec'` so obviously RSpec is undefined when this line is interpreted

I think it would be fine to explicitly require rails_event_store/rspec in spec_helper as @damireh suggested

**Comment by fidel** [comment]
Good point @mlomnicki, RSpec is now explicitly required bb561e8

Still you can do `gem "rails_event_store-rspec", require: false` and require it explicitly in your `rails_helper.rb`.

**Comment by mlomnicki** [comment]
@fidel nice one, works like a charm now :+1:

**Comment by jandudulski** [comment]
This issue is back since https://github.com/RailsEventStore/rails_event_store/commit/4b77b2ee4c2a7139b6cc88016127c35395bbd227 

I guess @pawelpacana removed runtime dependency by accident here?

**Comment by pawelpacana** [comment]
I find no other explanation 😱

**Comment by pawelpacana** [comment]
@jandudulski would you be kind enough to pull-request the change you desire?

Release train departing soon :)
