### ISSUE TITLE
Default serialization does not work in Ruby 3.1 for non-primitive values

### ISSUE THREAD

**Issue by katafrakt** [RailsEventStore/rails_event_store#1260]
Ruby 3.1 introduced Psych 4.0, which forces use of `safe_load` when calling `YAML.load` for non-core classes. I stumbled upon it because I use `BigDecimal` to store prices, which the land in the event. This was working fine in earlier Ruby versions:

```ruby
record = RubyEventStore::Record.new(event_id: "Abc", event_type: "test", data: BigDecimal("12.5"), metadata: {}, timestamp: Time.now,  valid_at: Time.now)
serialized = record.serialize(YAML)
serialized.deserialize(YAML)
#=> #<RubyEventStore::Record:0x00007fe900b0c868 @event_id="Abc", @data=0.125e2, @metadata={}, @event_type="test", @timestamp=2022-01-12 23:58:30.419385 +0100, @valid_at=2022-01-12 23:58:30.419387 +0100, @serialized_records={}>
```

However, the same does not work in 3.1:

```ruby
record = RubyEventStore::Record.new(event_id: "Abc", event_type: "test", data: BigDecimal("12.5"), metadata: {}, timestamp: Time.now,  valid_at: Time.now)
serialized = record.serialize(YAML)
serialized.deserialize(YAML)

Users/katafrakt/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/psych/class_loader.rb:99:in `find': Tried to load unspecified class: BigDecimal (Psych::DisallowedClass)                                                                             
	from /Users/katafrakt/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/psych/class_loader.rb:28:in `load'
	from (eval):2:in `big_decimal'
	from /Users/katafrakt/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:79:in `deserialize'
	from /Users/katafrakt/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:128:in `visit_Psych_Nodes_Scalar'
	from /Users/katafrakt/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
	from /Users/katafrakt/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
	from /Users/katafrakt/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
	from /Users/katafrakt/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:318:in `visit_Psych_Nodes_Document'
	from /Users/katafrakt/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
	from /Users/katafrakt/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
	from /Users/katafrakt/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
	from /Users/katafrakt/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/psych.rb:335:in `safe_load'
	from /Users/katafrakt/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/psych.rb:370:in `load'
	from /Users/katafrakt/dev/github/rails_event_store/ruby_event_store/lib/ruby_event_store/serialized_record.rb:57:in `deserialize'
	from (irb):6:in `<main>'
	from /Users/katafrakt/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/irb-1.4.1/exe/irb:11:in `<top (required)>'
	... 17 levels...
```

This could be simplified as:

```ruby
YAML.load(YAML.dump(BigDecimal("10"))) #=> exception in 3.1, works up to 3.0
YAML.unsafe_load(YAML.dump(BigDecimal("10"))) #=> 0.1e2
```

So, I think default serializer should be some adapter/proxy for a `YAML` class, which would call `unsafe_load` in its `load`, not just `YAML`.

**Comment by katafrakt** [comment]
This works as a workaround: https://github.com/katafrakt/yard_sale/commit/22299b2318de39f7b9bfa3bd60e4ed954b9b3e30

**Comment by pawelpacana** [comment]
Thank you for reporting this. I agree with your solution. I consider YAML serialization to be a low-cost-to-entry alternative to explicit types and schemas (achieved with different and with verbose description of the payload).

If `unsafe_load` was already present in past YAML versions distributed with Ruby > 2.6 then it is backwards compatible change too.

**Comment by katafrakt** [comment]
That's a good point. Turns out `unsafe_load` is a pretty recent addition. So I guess it should resort to duck typing: if `unsafe_load` is available, use it; if not, `load` _should_ work as the unsafe load.

**Comment by eric-at-carbodylab** [comment]
bump.  I had to implement the work-around that @katafrakt pointed to
