### ISSUE TITLE
Event data and metadata persisted as yaml strings

### ISSUE THREAD

**Issue by mzanini** [RailsEventStore/rails_event_store#1830]
### Error Description
Occasionally, but not all the time, an event is written to the DB with the `data` and `metadata` values as YAML strings instead of json, here an example where I step into the code and query the DB before the test fails:

```
[1] pry(#<RSpec::ExampleGroups::AggregatesProduce::WhenAProduceCreatedEventIsInTheStream>)> result = ActiveRecord::Base.connection.execute("SELECT * FROM event_store_events ORDER BY id DESC LIMIT 5")
=> #<PG::Result:0x0000ffff71698040 status=PGRES_TUPLES_OK ntuples=1 nfields=7 cmd_tuples=1>
[2] pry(#<RSpec::ExampleGroups::AggregatesProduce::WhenAProduceCreatedEventIsInTheStream>)> result.first
=> {"id"=>365,
 "event_id"=>"b144f5eb-c386-4e4c-891f-9d3e3e08e7e3",
 "event_type"=>"Events::ProduceCreated",
 "metadata"=>"\"---\\n:correlation_id: ef61c6d5-c164-43af-8b1f-799d976ce8e4\\n\"",
 "data"=>
  "\"---\\n:object:\\n  :id: 738\\n  :user_id: 3558\\n  :created_at: '2024-11-19T05:07:04.641Z'\\n  :updated_at: '2024-11-19T05:07:04.641Z'\\n  :description:\\n  :object: produce\\n:actor:\\n  :id: 3560\\n  :name: Mrs. Aleta Lind\\n  :email: raymundo_walter@dibbertlangworth.info\\n\"",
 "created_at"=>2024-11-19 05:07:04.653223 UTC,
 "valid_at"=>nil}
```

The test then fails with this error: 
```
Failure/Error: AggregateRoot::Repository.new.load(Aggregates::Produce.new, "produce:#{produce_id}")

     NoMethodError:
       undefined method `merge' for "---\n:correlation_id: ef61c6d5-c164-43af-8b1f-799d976ce8e4\n":String

                     record.metadata.merge(
                                    ^^^^^^
     # /usr/local/bundle/gems/ruby_event_store-2.13.0/lib/ruby_event_store/mappers/transformation/domain_event.rb:34:in `rescue in load'
     # /usr/local/bundle/gems/ruby_event_store-2.13.0/lib/ruby_event_store/mappers/transformation/domain_event.rb:21:in `load'
     # /usr/local/bundle/gems/ruby_event_store-2.13.0/lib/ruby_event_store/mappers/pipeline.rb:15:in `block in load'
     # /usr/local/bundle/gems/ruby_event_store-2.13.0/lib/ruby_event_store/mappers/pipeline.rb:15:in `each'
     # /usr/local/bundle/gems/ruby_event_store-2.13.0/lib/ruby_event_store/mappers/pipeline.rb:15:in `reduce'
     # /usr/local/bundle/gems/ruby_event_store-2.13.0/lib/ruby_event_store/mappers/pipeline.rb:15:in `load'
     # /usr/local/bundle/gems/ruby_event_store-2.13.0/lib/ruby_event_store/mappers/pipeline_mapper.rb:15:in `record_to_event'
     # /usr/local/bundle/gems/ruby_event_store-2.13.0/lib/ruby_event_store/mappers/instrumented_mapper.rb:19:in `block in record_to_event'
     # /usr/local/bundle/gems/ruby_event_store-2.13.0/lib/ruby_event_store/mappers/instrumented_mapper.rb:18:in `record_to_event'
     # /usr/local/bundle/gems/ruby_event_store-2.13.0/lib/ruby_event_store/mappers/instrumented_mapper.rb:19:in `block in record_to_event'
     # /usr/local/bundle/gems/ruby_event_store-2.13.0/lib/ruby_event_store/mappers/instrumented_mapper.rb:18:in `record_to_event'
     # /usr/local/bundle/gems/ruby_event_store-2.13.0/lib/ruby_event_store/specification_reader.rb:23:in `block (2 levels) in each'
     # /usr/local/bundle/gems/ruby_event_store-2.13.0/lib/ruby_event_store/specification_reader.rb:23:in `map'
     # /usr/local/bundle/gems/ruby_event_store-2.13.0/lib/ruby_event_store/specification_reader.rb:23:in `block in each'
     # /usr/local/bundle/gems/ruby_event_store-active_record-2.13.0/lib/ruby_event_store/active_record/batch_enumerator.rb:20:in `block in each'
     # /usr/local/bundle/gems/ruby_event_store-active_record-2.13.0/lib/ruby_event_store/active_record/batch_enumerator.rb:16:in `step'
     # /usr/local/bundle/gems/ruby_event_store-active_record-2.13.0/lib/ruby_event_store/active_record/batch_enumerator.rb:16:in `each'
     # /usr/local/bundle/gems/ruby_event_store-2.13.0/lib/ruby_event_store/specification_reader.rb:23:in `each'
     # /usr/local/bundle/gems/ruby_event_store-2.13.0/lib/ruby_event_store/specification_reader.rb:23:in `each'
     # /usr/local/bundle/gems/ruby_event_store-2.13.0/lib/ruby_event_store/specification.rb:172:in `each_batch'
     # /usr/local/bundle/gems/ruby_event_store-2.13.0/lib/ruby_event_store/specification.rb:184:in `each'
     # /usr/local/bundle/gems/ruby_event_store-2.13.0/lib/ruby_event_store/specification.rb:205:in `each'
     # /usr/local/bundle/gems/ruby_event_store-2.13.0/lib/ruby_event_store/specification.rb:205:in `reduce'
     # /usr/local/bundle/gems/ruby_event_store-2.13.0/lib/ruby_event_store/specification.rb:205:in `reduce'
     # /usr/local/bundle/gems/aggregate_root-2.13.0/lib/aggregate_root/repository.rb:10:in `load'
     # ./lib/aggregates/produce.rb:42:in `for_id'
     # ./spec/lib/aggregates/produce_spec.rb:6:in `block (2 levels) in <main>'
     # ./spec/lib/aggregates/produce_spec.rb:24:in `block (3 levels) in <main>'
     # ------------------
     # --- Caused by: ---
     # NoMethodError:
     #   undefined method `merge' for "---\n:correlation_id: ef61c6d5-c164-43af-8b1f-799d976ce8e4\n":String
     #
     #                 metadata: record.metadata.merge(timestamp: record.timestamp, valid_at: record.valid_at)
     #                                          ^^^^^^
     #   /usr/local/bundle/gems/ruby_event_store-2.13.0/lib/ruby_event_store/mappers/transformation/domain_event.rb:27:in `load'
```

### Expected Output
This is the output from when the test does not fail:

```
[1] pry(#<RSpec::ExampleGroups::AggregatesProduce::WhenAProduceCreatedEventIsInTheStream>)> result = ActiveRecord::Base.connection.execute("SELECT * FROM event_store_events ORDER BY id DESC LIMIT 5").first
=> {"id"=>350,
 "event_id"=>"26893e31-dc67-4844-b27c-e896ef54f99d",
 "event_type"=>"Events::ProduceCreated",
 "metadata"=>
  "{\"types\": {\"data\": {\"actor\": [\"Symbol\", {\"id\": [\"Symbol\", \"Integer\"], \"name\": [\"Symbol\", \"String\"], \"email\": [\"Symbol\", \"String\"]}], \"object\": [\"Symbol\", {\"id\": [\"Symbol\", \"Integer\"], \"unit\": [\"Symbol\", \"String\"], \"object\": [\"Symbol\", \"String\"], \"user_id\": [\"Symbol\", \"Integer\"], \"created_at\": [\"Symbol\", \"String\"], \"updated_at\": [\"Symbol\", \"String\"], \"description\": [\"Symbol\", \"NilClass\"]}]}, \"metadata\": {\"correlation_id\": [\"Symbol\", \"String\"]}}, \"correlation_id\": \"ab7f04a2-0ad3-4b27-9b38-bc610faaf3ee\"}",
 "data"=>
  "{\"actor\": {\"id\": 3440, \"name\": \"Ruthie Schneider\", \"email\": \"wai.sanford@lindgren.com\"}, \"object\": {\"id\": 713, \"object\": \"produce\", \"user_id\": 3438, \"created_at\": \"2024-11-19T05:04:16.380Z\", \"species_id\": 803, \"updated_at\": \"2024-11-19T05:04:16.380Z\", \"description\": null}}",
 "created_at"=>2024-11-19 05:04:16.392573 UTC,
 "valid_at"=>nil}
```

I have tried to insert breakpoints in the `ruby_event_store` code but in the end I just cannot figure out why sometimes this happens

**Comment by lukaszreszke** [comment]
Hi @mzanini,

It looks like the metadata doesn't have correct type. In the first test it is string. In the latter one it is hash. Do you modify the metadata in the implementation or in the spec itself? 

Would you share more code where it fails, or preferably some reproduction? That would help us a lot.

If you have the seed of failing test suite you could run rspec bisect to find out exact test order which fails.

**Comment by mzanini** [comment]
Ohhhhh I found out! This is totally my fault of course. In a test that gets executed earlier I replace the event store in `Rails.configuration.event_store` to prevent that test from publishing events that call event handlers. That event store is not configured to use JSON and therefore what is stored in the DB is not correct. Thanks a lot for the help! Great project!

**Comment by mzanini** [comment]
Related to this, it would be nice if there was a way to cancel even subscriptions after they have been created so that in my tests I can clear them out. I know when you create a subscription a method to cancel the subscription is returned but I subscribe in an initializer so there is no way for me to get to it in my tests.
