### ISSUE TITLE
bunded_context not passing on master

### ISSUE THREAD

**Issue by paneq** [RailsEventStore/rails_event_store#192]
```
/d/r/bounded_context (protobuf_mapper|✔) $ rm Gemfile.lock 
~/d/r/bounded_context (protobuf_mapper|✔) $ gem uninstall rails

Select gem to uninstall:
 1. rails-4.2.9
 2. rails-5.0.6
 3. rails-5.1.4
 4. rails-5.1.5
 5. All versions
> 3
Successfully uninstalled rails-5.1.4
~/d/r/bounded_context (protobuf_mapper|✔) $ gem uninstall rails

Select gem to uninstall:
 1. rails-4.2.9
 2. rails-5.0.6
 3. rails-5.1.5
 4. All versions
> 3
Successfully uninstalled rails-5.1.5
~/d/r/bounded_context (protobuf_mapper|✔) $ bundle install
Fetching gem metadata from https://rubygems.org/..........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using rake 10.5.0
Using abstract_type 0.0.7
Using concurrent-ruby 1.0.5
Using i18n 0.9.5
Using minitest 5.11.3
Using thread_safe 0.3.6
Using tzinfo 1.2.5
Using activesupport 5.1.5
Using builder 3.2.3
Using erubi 1.7.0
Using mini_portile2 2.3.0
Using nokogiri 1.8.2
Using rails-dom-testing 2.0.3
Using crass 1.0.3
Using loofah 2.2.0
Using rails-html-sanitizer 1.0.3
Using actionview 5.1.5
Using rack 2.0.4
Using rack-test 0.8.2
Using actionpack 5.1.5
Using nio4r 2.2.0
Using websocket-extensions 0.1.3
Using websocket-driver 0.6.5
Using actioncable 5.1.5
Using globalid 0.4.1
Using activejob 5.1.5
Using mini_mime 1.0.0
Using mail 2.7.0
Using actionmailer 5.1.5
Using activemodel 5.1.5
Using arel 8.0.0
Using activerecord 5.1.5
Using ice_nine 0.11.2
Using memoizable 0.4.2
Using adamantium 0.2.0
Using equalizer 0.0.11
Using anima 0.3.0
Using ast 2.4.0
Using bounded_context 0.23.0 from source at `.`
Using bundler 1.16.1
Using concord 0.1.5
Using diff-lcs 1.3
Using method_source 0.9.0
Using procto 0.0.3
Using morpher 0.2.6
Using parallel 1.12.1
Using parser 2.4.0.2
Using regexp_parser 0.4.9
Using unparser 0.2.6
Using mutant 0.8.14
Using rspec-support 3.6.0
Using rspec-core 3.6.0
Using mutant-rspec 0.8.14
Using thor 0.20.0
Using railties 5.1.5
Using sprockets 3.7.1
Using sprockets-rails 3.2.1
Fetching rails 5.1.5
Installing rails 5.1.5
Using rspec-expectations 3.6.0
Using rspec-mocks 3.6.0
Using rspec 3.6.0
Bundle complete! 6 Gemfile dependencies, 61 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
~/d/r/bounded_context (protobuf_mapper|✔) $ bundle exec rspec --seed 32630

Randomized with seed 32630
.......Could not find gem 'rails (= 5.1.4)' in any of the gem sources listed in your Gemfile.
Run `bundle install` to install missing gems.
F

Failures:

  1) BoundedContext::Generators should match content "require_relative '../lib/identity_access'\n"
     Failure/Error: @matcher.matches?(File.read(File.join(destination_root, actual)))
     
     Errno::ENOENT:
       No such file or directory @ rb_sysopen - /Users/rupert/develop/rails_event_store/bounded_context/spec/tmp/3ac5cdd9c72f67a391891cd5da29230e/identity_access/test/test_helper.rb
     # ./spec/generators_spec.rb:10:in `read'
     # ./spec/generators_spec.rb:10:in `block (3 levels) in <module:BoundedContext>'
     # ./spec/generators_spec.rb:118:in `expect_identity_access_test_helper'
     # ./spec/generators_spec.rb:82:in `block (2 levels) in <module:BoundedContext>'
     # ./spec/spec_helper.rb:48:in `block (2 levels) in <top (required)>'

Finished in 0.34378 seconds (files took 0.37888 seconds to load)
8 examples, 1 failure

Failed examples:

rspec ./spec/generators_spec.rb:80 # BoundedContext::Generators should match content "require_relative '../lib/identity_access'\n"

Randomized with seed 32630
```

**Comment by paneq** [comment]
`spec.add_development_dependency 'rails', '~> 5.1'` installs `5.1.5` now.

**Comment by paneq** [comment]
```
ENV['RAILS_VERSION'] ||= '5.1.4'
DUMMY_APP_NAME = "dummy_#{ENV['RAILS_VERSION'].gsub(".", "_")}"
TMP_ROOT   = File.join(__dir__, 'tmp')
DUMMY_ROOT = File.join(__dir__, DUMMY_APP_NAME)
raise "App #{DUMMY_APP_NAME} doesn't exist" unless File.exists?(DUMMY_ROOT)
```

tries using `5.1.4` which is not installed on CI (but might be installed on local machine historically)

**Comment by paneq** [comment]
```
Randomized with seed 8019
.......sh: 1: bin/rails: not found
F.
Failures:
  1) BoundedContext::Generators should match content "require_relative '../lib/identity_access'\n"
     Failure/Error: @matcher.matches?(File.read(File.join(destination_root, actual)))
     
     Errno::ENOENT:
       No such file or directory @ rb_sysopen - /home/travis/build/RailsEventStore/rails_event_store/bounded_context/spec/tmp/2e3b1651b7237127c845fd2d0828afe1/identity_access/test/test_helper.rb
     # ./spec/generators_spec.rb:10:in `read'
     # ./spec/generators_spec.rb:10:in `block (3 levels) in <module:BoundedContext>'
     # ./spec/generators_spec.rb:118:in `expect_identity_access_test_helper'
     # ./spec/generators_spec.rb:82:in `block (2 levels) in <module:BoundedContext>'
     # ./spec/spec_helper.rb:50:in `block (2 levels) in <top (required)>'
Finished in 0.26504 seconds (files took 0.35465 seconds to load)
9 examples, 1 failure
Failed examples:
rspec ./spec/generators_spec.rb:80 # BoundedContext::Generators should match content "require_relative '../lib/identity_access'\n"
```

**Comment by pawelpacana** [comment]
No `Gemfile.lock` involved?

**Comment by paneq** [comment]
@pawelpacana I am not sure what's going on... Everything looks good to me and it works locally. I wonder if that's a file system issue...

**Comment by paneq** [comment]
How is it possible that it fails due to `bin/rails: not found` for the same test even though that test is executed randomly in different order?

```
Randomized with seed 4491
.sh: 1: bin/rails: not found
F.......
Failures:
  1) BoundedContext::Generators should match content "require_relative '../lib/identity_access'\n"
     Failure/Error: @matcher.matches?(File.read(File.join(destination_root, actual)))
     
     Errno::ENOENT:
       No such file or directory @ rb_sysopen - /home/travis/build/RailsEventStore/rails_event_store/bounded_context/spec/tmp/1c3385dd3418728dec55b542f515dbe5/identity_access/test/test_helper.rb
     # ./spec/generators_spec.rb:10:in `read'
     # ./spec/generators_spec.rb:10:in `block (3 levels) in <module:BoundedContext>'
     # ./spec/generators_spec.rb:118:in `expect_identity_access_test_helper'
     # ./spec/generators_spec.rb:82:in `block (2 levels) in <module:BoundedContext>'
     # ./spec/spec_helper.rb:50:in `block (2 levels) in <top (required)>'
Finished in 0.31144 seconds (files took 0.39376 seconds to load)
9 examples, 1 failure
Failed examples:
rspec ./spec/generators_spec.rb:80 # BoundedContext::Generators should match content "require_relative '../lib/identity_access'\n"
```

**Comment by paneq** [comment]
```
Failures:
  1) BoundedContext::Generators should match content "require_relative '../lib/identity_access'\n"
     Failure/Error: @matcher.matches?(File.read(File.join(destination_root, actual)))
     
     Errno::ENOENT:
       No such file or directory @ rb_sysopen - /home/travis/build/RailsEventStore/rails_event_store/bounded_context/spec/tmp/02750d2054c8837caabe25356f896992/identity_access/test/test_helper.rb
     # ./spec/generators_spec.rb:10:in `read'
     # ./spec/generators_spec.rb:10:in `block (3 levels) in <module:BoundedContext>'
     # ./spec/generators_spec.rb:118:in `expect_identity_access_test_helper'
     # ./spec/generators_spec.rb:82:in `block (2 levels) in <module:BoundedContext>'
     # ./spec/spec_helper.rb:50:in `block (2 levels) in <top (required)>'
Finished in 0.3167 seconds (files took 0.40385 seconds to load)
9 examples, 1 failure
Failed examples:
rspec ./spec/generators_spec.rb:80 # BoundedContext::Generators should match content "require_relative '../lib/identity_access'\n"
```

**Comment by paneq** [comment]
```
~/d/r/bounded_context (master|✔) $ git add spec/dummy_5_1_5/bin
The following paths are ignored by one of your .gitignore files:
bounded_context/spec/dummy_5_1_5/bin
Use -f if you really want to add them.
~/d/r/bounded_context (master|✔) $ git add -f spec/dummy_5_1_5/bin
~/d/r/bounded_context (master|●6) $ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	new file:   spec/dummy_5_1_5/bin/bundle
	new file:   spec/dummy_5_1_5/bin/rails
	new file:   spec/dummy_5_1_5/bin/rake
	new file:   spec/dummy_5_1_5/bin/setup
	new file:   spec/dummy_5_1_5/bin/update
	new file:   spec/dummy_5_1_5/bin/yarn
```

**Comment by paneq** [comment]
```
~/d/r/bounded_context (master|✔) $ cat ../.gitignore
......
bin/
```

Why is this `bin` there?
