### ISSUE TITLE
Release 0.27

### ISSUE THREAD

**Issue by paneq** [RailsEventStore/rails_event_store#209]
* [x] rubygems
* [x] mention #126 in release notes
  * show what is no longer necessary
  * merge https://github.com/RailsEventStore/railseventstore.org/pull/18
* [x] #189 Protobuf
  * [x] mention that you can now serialize your events however you want: protbuf, messagepack, Apache Avro, BSON, Thrift, Cap’n Proto
  * [x] link to updated documentation
  * [x] write tutorial on how to use provided Protobuf mapper #227 
* [x] Document using RES without Rails
  * [x] Write
  * [x] Remove _edge_ markers in documentation and branches from Gemfile.
  * [x] Notify on Slack

**Comment by paneq** [comment]
```
make[1]: Entering directory '/Users/rupert/develop/rails_event_store/rails_event_store-browser'
Building browser frontend
yarn run v1.5.1
$ NODE_ENV=production node --harmony node_modules/.bin/webpack -p --bail
Hash: 33e397b83de444181091
Version: webpack 3.6.0
Time: 2960ms
                       Asset    Size  Chunks             Chunk Names
rails_event_store_browser.js  101 kB       0  [emitted]  main

ERROR in ./node_modules/css-loader?{"sourceMap":false}!./node_modules/sass-loader/lib/loader.js?{}!./src/style/style.scss
Module build failed: Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (59)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.5.3
    at module.exports (/Users/rupert/develop/rails_event_store/rails_event_store-browser/elm/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/Users/rupert/develop/rails_event_store/rails_event_store-browser/elm/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
    at Module.require (module.js:606:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/rupert/develop/rails_event_store/rails_event_store-browser/elm/node_modules/sass-loader/lib/loader.js:3:14)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
    at Module.require (module.js:606:17)
    at require (internal/module.js:11:18)
    at loadLoader (/Users/rupert/develop/rails_event_store/rails_event_store-browser/elm/node_modules/loader-runner/lib/loadLoader.js:13:17)
    at iteratePitchingLoaders (/Users/rupert/develop/rails_event_store/rails_event_store-browser/elm/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/Users/rupert/develop/rails_event_store/rails_event_store-browser/elm/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /Users/rupert/develop/rails_event_store/rails_event_store-browser/elm/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/Users/rupert/develop/rails_event_store/rails_event_store-browser/elm/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/Users/rupert/develop/rails_event_store/rails_event_store-browser/elm/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/Users/rupert/develop/rails_event_store/rails_event_store-browser/elm/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
    at NormalModule.doBuild (/Users/rupert/develop/rails_event_store/rails_event_store-browser/elm/node_modules/webpack/lib/NormalModule.js:182:3)
    at NormalModule.build (/Users/rupert/develop/rails_event_store/rails_event_store-browser/elm/node_modules/webpack/lib/NormalModule.js:275:15)
    at Compilation.buildModule (/Users/rupert/develop/rails_event_store/rails_event_store-browser/elm/node_modules/webpack/lib/Compilation.js:149:10)
    at factoryCallback (/Users/rupert/develop/rails_event_store/rails_event_store-browser/elm/node_modules/webpack/lib/Compilation.js:337:12)
    at factory (/Users/rupert/develop/rails_event_store/rails_event_store-browser/elm/node_modules/webpack/lib/NormalModuleFactory.js:241:5)
    at applyPluginsAsyncWaterfall (/Users/rupert/develop/rails_event_store/rails_event_store-browser/elm/node_modules/webpack/lib/NormalModuleFactory.js:94:13)
 @ ./src/style/style.scss 4:14-143
 @ ./src/index.js
 @ multi ./src/index.js
error An unexpected error occurred: "Command failed.
Exit code: 2
Command: sh
Arguments: -c NODE_ENV=production node --harmony node_modules/.bin/webpack -p --bail
Directory: /Users/rupert/develop/rails_event_store/rails_event_store-browser/elm
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/Users/rupert/develop/rails_event_store/rails_event_store-browser/elm/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
make[1]: *** [Makefile:29: public/rails_event_store_browser.js] Error 1
make[1]: Leaving directory '/Users/rupert/develop/rails_event_store/rails_event_store-browser'
make: *** [Makefile:27: build-rails_event_store-browser] Error 2
```

**Comment by pawelpacana** [comment]
I think I've seen it before. In case `node-sass` update doesn't solve it, we could possibly remove it.

**Comment by pawelpacana** [comment]
If you call `release` it calls `clean` and one of the steps:

https://github.com/RailsEventStore/rails_event_store/blob/master/rails_event_store-browser/Makefile#L41-L43

**Comment by pawelpacana** [comment]
I'd expect `0.27` browser release to be broken then. Let's release `0.27.1` right after this one is solved.

**Comment by valscion** [comment]
We've had to battle with `node-sass` and Yarn, too, and this is what we run on our CI to fix `node-sass` builds:

> Yarn doesn't seem to provide any other mechanism than a force-reinstallation
> of all packages instead of offering a `rebuild` command:
> https://github.com/yarnpkg/yarn/issues/756
> https://github.com/yarnpkg/yarn/issues/2069
> https://github.com/yarnpkg/yarn/issues/5271
> https://github.com/yarnpkg/yarn/pull/4750
> 
> As `yarn install --force` can timeout the build and does not use the offline
> cache, let's try to remove the node-sass and make `yarn` install the packages
> missing in `node_modules` by using `--check-files` flag

```
- run: rm -rf node_modules/node-sass
- run: yarn install --check-files --offline --frozen-lockfile
```

Back when we were using `npm`, we had `npm rebuild node-sass` which worked just as well.

**Comment by paneq** [comment]
> Let's release 0.27.1 right after this one is solved.

done.

**Comment by paneq** [comment]
@valscion thanks for the info but why is that necessary at all is beyond me :)

**Comment by valscion** [comment]
Yeah. I'd love it if it wasn't necessary. Compatibility issues with Yarn and native dependencies (especially `node-sass`) is one area where I really hope Yarn would step up and fix somehow. I bet it's a hugely complicated issue :smile:
