### ISSUE TITLE
Failure/Error: Thread.pass Timeout::Error: execution expired

### ISSUE THREAD

**Issue by fidel** [RailsEventStore/rails_event_store#254]
I'm experiencing random failures of this test case on my development environment. It occurs while running `rspec` command or `make test`. Any clues? 

Ruby: 2.5.0
branch: master 
revision: 494593054a0ac50b63f2f55b55420a3ae3dff0d1

```
 c/R/rails_event_store/ruby_event_store {fluent-api} $ make mutate SUBJECT=RubyEventStore::NewClient                                                                                                                                                                   8s 748ms 
Running unit tests

Randomized with seed 54976
...............................F................................................................................................................................................................................................................................................
..

Failures:

  1) RubyEventStore::Client dynamic subscribe v2 temporary subscriptions don't affect other threads
     Failure/Error: Thread.pass
     
     Timeout::Error:
       execution expired
     # ./lib/ruby_event_store/in_memory_repository.rb:107:in `pass'
     # ./lib/ruby_event_store/in_memory_repository.rb:107:in `append_with_synchronize'
     # ./lib/ruby_event_store/in_memory_repository.rb:96:in `add_to_stream'
     # ./lib/ruby_event_store/in_memory_repository.rb:15:in `append_to_stream'
     # ./lib/ruby_event_store/client.rb:30:in `append_to_stream'
     # ./lib/ruby_event_store/client.rb:16:in `publish_events'
     # ./lib/ruby_event_store/client.rb:24:in `publish_event'
     # ./spec/subscription_spec.rb:471:in `block (5 levels) in <module:RubyEventStore>'
     # ./spec/subscription_spec.rb:471:in `times'
     # ./spec/subscription_spec.rb:471:in `block (4 levels) in <module:RubyEventStore>'
     # ./lib/ruby_event_store/client.rb:157:in `call'
     # ./spec/subscription_spec.rb:472:in `block (3 levels) in <module:RubyEventStore>'
     # ./spec/subscription_spec.rb:34:in `block (3 levels) in <module:RubyEventStore>'
     # ./spec/subscription_spec.rb:28:in `silence_stderr'
     # ./spec/subscription_spec.rb:34:in `block (2 levels) in <module:RubyEventStore>'
     # ./spec/spec_helper.rb:11:in `block (2 levels) in <top (required)>'

Finished in 6.2 seconds (files took 0.46337 seconds to load)
274 examples, 1 failure

Failed examples:

rspec ./spec/subscription_spec.rb:462 # RubyEventStore::Client dynamic subscribe v2 temporary subscriptions don't affect other threads

Randomized with seed 54976

make: *** [test] Error 1
```

**Comment by paneq** [comment]
da faq...

**Comment by paneq** [comment]
ah...

```
specify "temporary subscriptions don't affect other threads" do
        h1,h2,h3,h4 = 4.times.map{Subscribers::ValidHandler.new}
        big_number = 2_000
        thread = Thread.new do
          client.within do
            big_number.times{ client.publish_event(ProductAdded.new) }
          end.subscribe_to_all_events(h3).subscribe(h4, to: ProductAdded).call
        end
        client.within do
          big_number.times{ client.publish_event(OrderCreated.new) }
        end.subscribe_to_all_events(h1).subscribe(h2, to: OrderCreated).call
        thread.join
```

I suspect your machine is just too slow execute this threading stress-test. Consider making timeout configurable as (`5*TEST_FACTOR`) maybe,

**Comment by paneq** [comment]
Hypothesis. It uses InMemoryRepo. This is now slower because previously InMemoryRepo was not serializing the data. Now it is serialized before the repo and thus the whole thing is slower. 

I suggest rewriting as:

```
specify "temporary subscriptions don't affect other threads" do
       exchanger = Concurrent::Exchanger.new
        h1,h2,h3,h4 = 4.times.map{Subscribers::ValidHandler.new}
        big_number = 10
        thread = Thread.new do
          client.within do
            exchanger.exchange!('love_marta', timeout)
            big_number.times{ client.publish_event(ProductAdded.new) }
            exchanger.exchange!('love_robert', timeout)
          end.subscribe_to_all_events(h3).subscribe(h4, to: ProductAdded).call
        end
        client.within do
          exchanger.exchange!('love_marta', timeout)
          big_number.times{ client.publish_event(OrderCreated.new) }
          exchanger.exchange!('love_robert', timeout)
        end.subscribe_to_all_events(h1).subscribe(h2, to: OrderCreated).call
        thread.join
```

that sounds like a much better and faster way to ensure both threads are withing `within` block when publishing then the brute-force approach I used originally 

@fidel  :)

**Comment by pawelpacana** [comment]
More affected builds: https://travis-ci.org/RailsEventStore/rails_event_store/jobs/362104286
