### ISSUE TITLE
infinite mutations on master in rails_event_store-browser

### ISSUE THREAD

**Issue by paneq** [RailsEventStore/rails_event_store#277]
```
(103/1263) 100% - killtime: 42.26s runtime: 1520.70s overhead: 1478.44s
28
evil:RailsEventStore::Browser::EventsController#serialize_event:/home/travis/build/RailsEventStore/rails_event_store/rails_event_store-browser/app/controllers/rails_event_store/browser/events_controller.rb:15:c8513
104
evil:RailsEventStore::Browser::EventsController#show:/home/travis/build/RailsEventStore/rails_event_store/rails_event_store-browser/app/controllers/rails_event_store/browser/events_controller.rb:4:47261
```

**Comment by paneq** [comment]
For the future - how to handle such case:

### 1

```
commit 1a5e7eb5202ae62cbd7f5041f1e21b0c17dac6d5 (HEAD -> mutant_debugging2, origin/mutant_debugging2)
Author: Robert Pankowecki <robert.pankowecki@gmail.com>
Date:   Sat Apr 7 09:22:41 2018 +0200

    Debug infinite mutations

diff --git a/rails_event_store-browser/Gemfile b/rails_event_store-browser/Gemfile
index a456956..fa727a9 100644
--- a/rails_event_store-browser/Gemfile
+++ b/rails_event_store-browser/Gemfile
@@ -10,3 +10,4 @@ gem 'bounded_context',                 path: '../bounded_context'
 if v = ENV['RAILS_VERSION']
   gem 'rails', v
 end
+gem 'mutant', github: 'paneq/mutant'
```

push and run on CI.
Check which mutation is being run inifinitely in the output

### 2

locally:

* bundle show mutant
* vim `lib/mutant/mutation.rb`

```
    # SHA1 sum of source and subject identification
    #
    # @return [String]
    def sha1
      ident = subject.identification.gsub("/Users/rupert/develop/rails_event_store", "/home/travis/build/RailsEventStore/rails_event_store") 
      Digest::SHA1.hexdigest(ident + CODE_DELIMITER + source)
    end
    memoize :sha1
```

edit sha1 to be stable between local env and CI

**Comment by paneq** [comment]
### 3

locally

* vim lib/mutant/mutation.rb

```
    # Mutation code
    #
    # @return [String]
    def code
      c = sha1[CODE_RANGE]
      puts source if c == "c8513"
      c
    end
    memoize :code
```

`c8513` is from the output on CI :

```
28
evil:...rails_event_store-browser/app/controllers/rails_event_store/browser/events_controller.rb:15:c8513
```

**Comment by paneq** [comment]
### 4

run `env CI=true make mutate` locally. Observe the output:

```
def serialize_event(event)
  self
end
evil:RailsEventStore::Browser::EventsController#serialize_event:/Users/rupert/develop/rails_event_store/rails_event_store-browser/app/controllers/rails_event_store/browser/events_controller.rb:15:c8513
```

**Comment by paneq** [comment]
When I introduce the change manually I get:

```
Randomized with seed 27260
......................FF..

Failures:

  1) RailsEventStore::Browser 
     Failure/Error: render json: { data: serialize_event(event) }, content_type: 'application/vnd.api+json'
     
     SystemStackError:
       stack level too deep
     # ./app/controllers/rails_event_store/browser/events_controller.rb:6:in `show'
     # /Users/rupert/develop/rails_event_store/rails_event_store/lib/rails_event_store/middleware.rb:10:in `call'
     # ./spec/support/json_api_lint.rb:25:in `call'
     # ./spec/api_spec.rb:360:in `get'
     # ./spec/api_spec.rb:170:in `block (2 levels) in <module:RailsEventStore>'
     # ./spec/support/mutant_timeout.rb:5:in `block (2 levels) in <top (required)>'

  2) RailsEventStore::Browser should text "Events in foo/bar.xml"
     Failure/Error:
       within('.event__body') do
         expect(page).to have_content(foo_bar_event.event_id)
         expect(page).to have_content(%Q[{ "timestamp": "#{foo_bar_event.metadata[:timestamp].as_json}" ])
         expect(page).to have_content(%Q[{ "foo": "bar" }])
       end
     
     Capybara::ElementNotFound:
       Unable to find visible css ".event__body"
     # ./spec/ui_spec.rb:28:in `block (2 levels) in <module:RailsEventStore>'
     # ./spec/support/mutant_timeout.rb:5:in `block (2 levels) in <top (required)>'

Finished in 7.1 seconds (files took 3.49 seconds to load)
26 examples, 2 failures

Failed examples:

rspec ./spec/api_spec.rb:168 # RailsEventStore::Browser 
rspec ./spec/ui_spec.rb:11 # RailsEventStore::Browser should text "Events in foo/bar.xml"
```

So I suspect there is some issue in handling SystemStackError

**Comment by paneq** [comment]
I think even though we use much newer ruby we are affected by https://github.com/mbj/mutant#the-crash--stuck-problem-mri

**Comment by pawelpacana** [comment]
Would it crash on JRuby?

**Comment by paneq** [comment]
Would it fork on JRuby ?

**Comment by paneq** [comment]
* https://bugs.ruby-lang.org/issues/14181
* https://github.com/paneq/mutant/commit/d64232beb63b0f52abdca259bb656cf71996f01c

**Comment by paneq** [comment]
Interesting output https://travis-ci.org/RailsEventStore/rails_event_store/jobs/363451813

**Comment by paneq** [comment]
I thought we would inifinitely wait in that loop from https://github.com/paneq/mutant/commit/d64232beb63b0f52abdca259bb656cf71996f01c but it seems we might never reach it... maybe (guess) we never finish reading

```
      def parent(reader, writer, &block)
        pid = process.fork do
          child(reader, writer, &block)
        end

        writer.close
        marshal.load(reader)
      ensure
```

I am not sure what `marshal.load(reader` does.

**Comment by paneq** [comment]
I tried

```
      def parent(reader, writer, &block)
        pid = process.fork do
          child(reader, writer, &block)
        end

        writer.close
        puts "reading... #{pid}"
        v = reader.read
        puts "read... #{pid} #{v.class}"
        marshal.load(v)
      ensure
	      loop do
          break if process.waitpid(pid, Process::WNOHANG)
        end if pid
      end
```

and there were 2 more "reading..." than "read..." in the output. It gets stuck on reading from the pipe which child process should write to.

adding `ensure` does not help:

```
      def child(reader, writer, &block)
        reader.close
        writer.binmode
        writer.syswrite(marshal.dump(result(&block)))
      ensure
        writer.close
      end
```

**Comment by paneq** [comment]
I suggested removing mutation testing in `res-browser`. Alternative'y we can not mutate controllers but there is not much left when we disable that.

**Comment by paneq** [comment]
https://bugs.ruby-lang.org/issues/10443

**Comment by pawelpacana** [comment]
Alternative idea: mutation testing on provided docker container, if we find linux configuration that works.

**Comment by paneq** [comment]
good idea, big IF

**Comment by paneq** [comment]
The reliability seemed to improve

### Next Tasks:

* [ ] rails_event_store-rspec mutations on CircleCI
* [ ] ruby_event_store mutations on CircleCI
* [ ] rails_event_store mutations on CircleCI
* [ ] aggregate_root cache gems on CircleCI
* [ ] bounded_context cache gems on CircleCI
* [ ] rails_event_store-browser cache gems on CircleCI
* [ ] rails_event_store-browser cache npm packages on CircleCI
* [ ] rails_event_store_active_record cache gems on CircleCI
* [ ] rails_event_store-rspec cache gems on CircleCI
* [ ] ruby_event_store cache gems on CircleCI
* [ ] rails_event_store cache gems on CircleCI
