### ISSUE TITLE
CircleCI experiment

### ISSUE THREAD

**Issue by paneq** [RailsEventStore/rails_event_store#286]

**Comment by paneq** [comment]
```
circleci@a752b4350a2d:~$ which rspec
/usr/local/bundle/bin/rspec
circleci@a752b4350a2d:~$ rspec --version
RSpec 3.6
  - rspec-core 3.6.0
  - rspec-expectations 3.6.0
  - rspec-mocks 3.6.0
  - rspec-support 3.6.0
circleci@a752b4350a2d:~$ cd /home/circleci/project/aggregate_root
circleci@a752b4350a2d:~/project/aggregate_root$ bundle exec rspec
bundler: failed to load command: rspec (/usr/local/bundle/bin/rspec)
Gem::Exception: can't find executable rspec for gem rspec-core. rspec-core is not currently included in the bundle, perhaps you meant to add it to your Gemfile?
  /usr/local/lib/ruby/site_ruby/2.4.0/bundler/rubygems_integration.rb:458:in `block in replace_bin_path'
  /usr/local/lib/ruby/site_ruby/2.4.0/bundler/rubygems_integration.rb:489:in `block in replace_bin_path'
  /usr/local/bundle/bin/rspec:29:in `<top (required)>'
circleci@a752b4350a2d:~/project/aggregate_root$ cat Gemfile.lock | grep rspec
    mutant-rspec (0.8.14)
      rspec-core (>= 3.4.0, < 3.7.0)
    rspec (3.6.0)
      rspec-core (~> 3.6.0)
      rspec-expectations (~> 3.6.0)
      rspec-mocks (~> 3.6.0)
    rspec-core (3.6.0)
      rspec-support (~> 3.6.0)
    rspec-expectations (3.6.0)
      rspec-support (~> 3.6.0)
    rspec-mocks (3.6.0)
      rspec-support (~> 3.6.0)
    rspec-support (3.6.0)
  mutant-rspec (~> 0.8.14)
  rspec (~> 3.6)
circleci@a752b4350a2d:~/project/aggregate_root$ bundle show rspec
Could not find gem 'rspec'.
```

**Comment by paneq** [comment]
```
circleci@a752b4350a2d:~/project/aggregate_root$ bundle install
Using concurrent-ruby 1.0.5
Using i18n 1.0.0
Using minitest 5.11.3
Using thread_safe 0.3.6
Using tzinfo 1.2.5
Using activesupport 5.2.0
Using activemodel 5.2.0
Using arel 9.0.0
Using activerecord 5.2.0
Using activerecord-import 0.22.0
Using bundler 1.16.1
Using mysql2 0.4.10
Using pg 0.21.0
Using ruby_event_store 0.27.1 from source at `../../../ruby_event_store`
Using rails_event_store_active_record 0.27.1 from source at `../..`
Using sqlite3 1.3.13
Bundle complete! 6 Gemfile dependencies, 16 gems now installed.
Bundled gems are installed into `/usr/local/bundle`
circleci@a752b4350a2d:~/project/aggregate_root$ bundle install | grep rspec
```

**Comment by paneq** [comment]
seems like bundler is not installing development dependencies...

**Comment by paneq** [comment]
## Bundler settings

```
silence_root_warning
  Set via BUNDLE_SILENCE_ROOT_WARNING: true
app_config
  Set via BUNDLE_APP_CONFIG: "/usr/local/bundle"
bin
  Set via BUNDLE_BIN: "/usr/local/bundle/bin"
path
  Set via BUNDLE_PATH: "/usr/local/bundle"
gemfile
  Set via BUNDLE_GEMFILE: "/home/circleci/project/rails_event_store_active_record/spec/without_rails/Gemfile"
```

**Comment by paneq** [comment]
```
circleci@a752b4350a2d:/usr/local/bundle$ env | grep BUNDLE
BUNDLE_SILENCE_ROOT_WARNING=1
BUNDLE_APP_CONFIG=/usr/local/bundle
BUNDLE_BIN=/usr/local/bundle/bin
BUNDLE_PATH=/usr/local/bundle
BUNDLER_VERSION=1.16.1
```

**Comment by paneq** [comment]
```
install: ## Install gem dependencies
	@echo "Installing gem dependencies"
	@bundle install
	@echo "Installing v1_v2_schema_migration gem dependencies"
	@BUNDLE_GEMFILE=spec/v1_v2_schema_migration/Gemfile bundle install
	@BUNDLE_GEMFILE=spec/without_rails/Gemfile bundle install
```

something, somewhere is remembering this BUNDLE_GEMFILE location...

**Comment by paneq** [comment]
https://github.com/bundler/bundler/issues/6162

**Comment by paneq** [comment]
> We've also encountered similar-but-not-quite-the-same problems with monorepo projects
