### ISSUE TITLE
res-deprecated-read-api-migrator did not work

### ISSUE THREAD

**Issue by paneq** [RailsEventStore/rails_event_store#406]
```
	44: from /Users/rupert/.rbenv/versions/2.5.0/bin/res-deprecated-read-api-migrator:23:in `<main>'
	43: from /Users/rupert/.rbenv/versions/2.5.0/bin/res-deprecated-read-api-migrator:23:in `load'
	42: from /Users/rupert/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ruby_event_store-0.31.1/exe/res-deprecated-read-api-migrator:19:in `<top (required)>'
	41: from /Users/rupert/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/parser-2.5.1.2/lib/parser/runner.rb:13:in `go'
	40: from /Users/rupert/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/parser-2.5.1.2/lib/parser/runner.rb:35:in `execute'
	39: from /Users/rupert/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/parser-2.5.1.2/lib/parser/runner.rb:174:in `process_all_input'
	38: from /Users/rupert/.rbenv/versions/2.5.0/lib/ruby/2.5.0/benchmark.rb:293:in `measure'
	37: from /Users/rupert/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/parser-2.5.1.2/lib/parser/runner.rb:176:in `block in process_all_input'
	36: from /Users/rupert/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/parser-2.5.1.2/lib/parser/runner.rb:196:in `process_files'
	35: from /Users/rupert/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/parser-2.5.1.2/lib/parser/runner.rb:196:in `each'
	34: from /Users/rupert/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/parser-2.5.1.2/lib/parser/runner.rb:207:in `block in process_files'
	33: from /Users/rupert/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/parser-2.5.1.2/lib/parser/runner.rb:214:in `process_buffer'
	32: from /Users/rupert/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ruby_event_store-0.31.1/lib/ruby_event_store/deprecated_read_api_runner.rb:29:in `process'
	31: from /Users/rupert/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/parser-2.5.1.2/lib/parser/rewriter.rb:26:in `rewrite'
	30: from /Users/rupert/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ast-2.4.0/lib/ast/processor/mixin.rb:259:in `process'
	29: from /Users/rupert/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/parser-2.5.1.2/lib/parser/ast/processor.rb:11:in `process_regular_node'
	28: from /Users/rupert/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ast-2.4.0/lib/ast/processor/mixin.rb:275:in `process_all'
	27: from /Users/rupert/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ast-2.4.0/lib/ast/processor/mixin.rb:275:in `map'
	26: from /Users/rupert/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ast-2.4.0/lib/ast/processor/mixin.rb:276:in `block in process_all'
	25: from /Users/rupert/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ast-2.4.0/lib/ast/processor/mixin.rb:259:in `process'
	24: from /Users/rupert/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/parser-2.5.1.2/lib/parser/ast/processor.rb:11:in `process_regular_node'
	23: from /Users/rupert/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ast-2.4.0/lib/ast/processor/mixin.rb:275:in `process_all'
	22: from /Users/rupert/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ast-2.4.0/lib/ast/processor/mixin.rb:275:in `map'
	21: from /Users/rupert/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ast-2.4.0/lib/ast/processor/mixin.rb:276:in `block in process_all'
	20: from /Users/rupert/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ast-2.4.0/lib/ast/processor/mixin.rb:259:in `process'
	19: from /Users/rupert/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/parser-2.5.1.2/lib/parser/ast/processor.rb:11:in `process_regular_node'
	18: from /Users/rupert/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ast-2.4.0/lib/ast/processor/mixin.rb:275:in `process_all'
	17: from /Users/rupert/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ast-2.4.0/lib/ast/processor/mixin.rb:275:in `map'
	16: from /Users/rupert/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ast-2.4.0/lib/ast/processor/mixin.rb:276:in `block in process_all'
	15: from /Users/rupert/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ast-2.4.0/lib/ast/processor/mixin.rb:259:in `process'
	14: from /Users/rupert/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/parser-2.5.1.2/lib/parser/ast/processor.rb:143:in `on_def'
	13: from /Users/rupert/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ast-2.4.0/lib/ast/processor/mixin.rb:259:in `process'
	12: from /Users/rupert/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ruby_event_store-0.31.1/lib/ruby_event_store/deprecated_read_api_rewriter.rb:9:in `on_send'
	11: from /Users/rupert/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/astrolabe-1.3.1/lib/astrolabe/node.rb:181:in `each_descendant'
	10: from /Users/rupert/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/astrolabe-1.3.1/lib/astrolabe/node.rb:243:in `visit_descendants_with_types'
	 9: from /Users/rupert/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/astrolabe-1.3.1/lib/astrolabe/node.rb:243:in `each'
	 8: from /Users/rupert/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/astrolabe-1.3.1/lib/astrolabe/node.rb:246:in `block in visit_descendants_with_types'
	 7: from /Users/rupert/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/astrolabe-1.3.1/lib/astrolabe/node.rb:243:in `visit_descendants_with_types'
	 6: from /Users/rupert/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/astrolabe-1.3.1/lib/astrolabe/node.rb:243:in `each'
	 5: from /Users/rupert/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/astrolabe-1.3.1/lib/astrolabe/node.rb:246:in `block in visit_descendants_with_types'
	 4: from /Users/rupert/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/astrolabe-1.3.1/lib/astrolabe/node.rb:243:in `visit_descendants_with_types'
	 3: from /Users/rupert/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/astrolabe-1.3.1/lib/astrolabe/node.rb:243:in `each'
	 2: from /Users/rupert/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/astrolabe-1.3.1/lib/astrolabe/node.rb:245:in `block in visit_descendants_with_types'
	 1: from /Users/rupert/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ruby_event_store-0.31.1/lib/ruby_event_store/deprecated_read_api_rewriter.rb:9:in `block in on_send'
/Users/rupert/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ruby_event_store-0.31.1/lib/ruby_event_store/deprecated_read_api_rewriter.rb:13:in `on_send': undefined method `join' for nil:NilClass (NoMethodError)
```

**Comment by paneq** [comment]
Given:

```ruby
    def on_send(node)
      node.each_descendant(:send) { |desc_node| on_send(desc_node) }

      _, method_name, *args = node.children
      replace_range = node.location.selector
      puts replace_range.inspect
      puts node.inspect if replace_range.nil?
```

Then:

```
#<Parser::Source::Range app/common/command_executor.rb 636...641>
#<Parser::Source::Range app/common/command_executor.rb 676...680>
#<Parser::Source::Range app/common/command_executor.rb 532...545>
nil
s(:send,
  s(:ivar, :@bus), :call,
  s(:lvar, :command))
Failed on: app/common/command_executor.rb
```

```
  def execute(command)
    @event_store.publish_event(CommandIssued.strict(
      company_id:   command.company_id,
      command_type: command.class.to_s,
      command_data: command.to_h,
    ))
    @bus.(command)
  end
```

**Comment by paneq** [comment]
I added `return if replace_range.nil?` to the code and it worked on my whole project beautifully!

**Comment by pawelpacana** [comment]
Fixed

**Comment by paneq** [comment]
Cool! Thanks!
