### ISSUE TITLE
MySQL adapter fails on MySQL 8.0

### ISSUE THREAD

**Issue by pawelpacana** [RailsEventStore/rails_event_store#697]
When running `rails_event_store_active_record` tests against MySQL 8.0 there are several errors that did not exist when running against MySQL 5.7. 

My guess is that something changed in the way index violations are reported and we rely on them in https://github.com/RailsEventStore/rails_event_store/blob/d7e49958c5ac3242469a282994f05448cc4d9119/rails_event_store_active_record/lib/rails_event_store_active_record/index_violation_detector.rb

```
 C/rails_event_store/rails_event_store_active_record{} $ env DATABASE_URL="mysql2://root:secret@127.0.0.1/rails_event_store?pool=5" make test
Running unit tests

Randomized with seed 23136
.................................F...........................F...............................F........

Failures:

  1) RailsEventStoreActiveRecord::EventRepository behaves like event_repository does not allow linking same event twice in a stream
     Failure/Error: example.run

       expected RubyEventStore::EventDuplicatedInStream, got #<RubyEventStore::WrongExpectedEventVersion: RubyEventStore::WrongExpectedEventVersion> with backtrace:
         # ./lib/rails_event_store_active_record/event_repository.rb:104:in `raise_error'
         # ./lib/rails_event_store_active_record/event_repository.rb:97:in `rescue in add_to_stream'
         # ./lib/rails_event_store_active_record/event_repository.rb:71:in `add_to_stream'
         # ./lib/rails_event_store_active_record/event_repository.rb:26:in `link_to_stream'
         # /Users/pawel/Code/rails_event_store/ruby_event_store/lib/ruby_event_store/spec/event_repository_lint.rb:880:in `block (3 levels) in <module:RubyEventStore>'
         # /Users/pawel/Code/rails_event_store/ruby_event_store/lib/ruby_event_store/spec/event_repository_lint.rb:879:in `block (2 levels) in <module:RubyEventStore>'
         # ./spec/event_repository_spec.rb:14:in `block (2 levels) in <module:RailsEventStoreActiveRecord>'
         # /Users/pawel/Code/rails_event_store/support/helpers/mutant_timeout.rb:8:in `block (2 levels) in <top (required)>'
     Shared Example Group: :event_repository called from ./spec/event_repository_spec.rb:29
     # /Users/pawel/Code/rails_event_store/ruby_event_store/lib/ruby_event_store/spec/event_repository_lint.rb:879:in `block (2 levels) in <module:RubyEventStore>'
     # ./spec/event_repository_spec.rb:14:in `block (2 levels) in <module:RailsEventStoreActiveRecord>'
     # /Users/pawel/Code/rails_event_store/support/helpers/mutant_timeout.rb:8:in `block (2 levels) in <top (required)>'

  2) RailsEventStoreActiveRecord::EventRepository behaves like event_repository does not allow same event twice in a stream
     Failure/Error: example.run

       expected RubyEventStore::EventDuplicatedInStream, got #<RubyEventStore::WrongExpectedEventVersion: RubyEventStore::WrongExpectedEventVersion> with backtrace:
         # ./lib/rails_event_store_active_record/event_repository.rb:104:in `raise_error'
         # ./lib/rails_event_store_active_record/event_repository.rb:97:in `rescue in add_to_stream'
         # ./lib/rails_event_store_active_record/event_repository.rb:71:in `add_to_stream'
         # ./lib/rails_event_store_active_record/event_repository.rb:15:in `append_to_stream'
         # /Users/pawel/Code/rails_event_store/ruby_event_store/lib/ruby_event_store/spec/event_repository_lint.rb:850:in `block (3 levels) in <module:RubyEventStore>'
         # /Users/pawel/Code/rails_event_store/ruby_event_store/lib/ruby_event_store/spec/event_repository_lint.rb:849:in `block (2 levels) in <module:RubyEventStore>'
         # ./spec/event_repository_spec.rb:14:in `block (2 levels) in <module:RailsEventStoreActiveRecord>'
         # /Users/pawel/Code/rails_event_store/support/helpers/mutant_timeout.rb:8:in `block (2 levels) in <top (required)>'
     Shared Example Group: :event_repository called from ./spec/event_repository_spec.rb:29
     # /Users/pawel/Code/rails_event_store/ruby_event_store/lib/ruby_event_store/spec/event_repository_lint.rb:849:in `block (2 levels) in <module:RubyEventStore>'
     # ./spec/event_repository_spec.rb:14:in `block (2 levels) in <module:RailsEventStoreActiveRecord>'
     # /Users/pawel/Code/rails_event_store/support/helpers/mutant_timeout.rb:8:in `block (2 levels) in <top (required)>'

  3) RailsEventStoreActiveRecord::EventRepository behaves like event_repository does not allow same event twice
     Failure/Error: example.run

       expected RubyEventStore::EventDuplicatedInStream, got #<RubyEventStore::WrongExpectedEventVersion: RubyEventStore::WrongExpectedEventVersion> with backtrace:
         # ./lib/rails_event_store_active_record/event_repository.rb:104:in `raise_error'
         # ./lib/rails_event_store_active_record/event_repository.rb:97:in `rescue in add_to_stream'
         # ./lib/rails_event_store_active_record/event_repository.rb:71:in `add_to_stream'
         # ./lib/rails_event_store_active_record/event_repository.rb:15:in `append_to_stream'
         # /Users/pawel/Code/rails_event_store/ruby_event_store/lib/ruby_event_store/spec/event_repository_lint.rb:865:in `block (3 levels) in <module:RubyEventStore>'
         # /Users/pawel/Code/rails_event_store/ruby_event_store/lib/ruby_event_store/spec/event_repository_lint.rb:864:in `block (2 levels) in <module:RubyEventStore>'
         # ./spec/event_repository_spec.rb:14:in `block (2 levels) in <module:RailsEventStoreActiveRecord>'
         # /Users/pawel/Code/rails_event_store/support/helpers/mutant_timeout.rb:8:in `block (2 levels) in <top (required)>'
     Shared Example Group: :event_repository called from ./spec/event_repository_spec.rb:29
     # /Users/pawel/Code/rails_event_store/ruby_event_store/lib/ruby_event_store/spec/event_repository_lint.rb:864:in `block (2 levels) in <module:RubyEventStore>'
     # ./spec/event_repository_spec.rb:14:in `block (2 levels) in <module:RailsEventStoreActiveRecord>'
     # /Users/pawel/Code/rails_event_store/support/helpers/mutant_timeout.rb:8:in `block (2 levels) in <top (required)>'

Finished in 1 minute 16.22 seconds (files took 0.93133 seconds to load)
102 examples, 3 failures

Failed examples:

rspec ./spec/event_repository_spec.rb[1:1:48] # RailsEventStoreActiveRecord::EventRepository behaves like event_repository does not allow linking same event twice in a stream
rspec ./spec/event_repository_spec.rb[1:1:46] # RailsEventStoreActiveRecord::EventRepository behaves like event_repository does not allow same event twice in a stream
rspec ./spec/event_repository_spec.rb[1:1:47] # RailsEventStoreActiveRecord::EventRepository behaves like event_repository does not allow same event twice

Randomized with seed 23136
```

**Comment by pawelpacana** [comment]
Relevant: https://github.com/RailsEventStore/rails_event_store/blob/2d35c7de6918177485735df73b17c7460531e8bc/rails_event_store_active_record/lib/rails_event_store_active_record/event_repository.rb#L100-L105

**Comment by pawelpacana** [comment]
It makes sense to introduce at least two recent releases of the same database engine into testing matrix — at least for MySQL.

Related: current testing matrix https://docs.google.com/spreadsheets/d/1RUW2MDdfBOhD0s31xslTIyuffGTIEj4p-w9K3BMQW40/edit#gid=0

**Comment by pawelpacana** [comment]
Errors from v5.7:

```
Mysql2::Error: Duplicate entry 'a1b49edb-7636-416f-874a-88f94b859bef' for key 'PRIMARY': INSERT INTO `event_store_events` (`id`, `event_type`, `metadata`, `data`, `created_at`) VALUES ('a1b49edb-7636-416f-874a-88f94b859bef', 'SRecordTestEvent', x'7b7d', x'7b7d', '2020-01-27 22:50:25')
Mysql2::Error: Duplicate entry 'flow-a1b49edb-7636-416f-874a-88f94b859bef' for key 'index_event_store_events_in_streams_on_stream_and_event_id': INSERT INTO `event_store_events_in_streams` (`stream`,`position`,`event_id`,`created_at`) VALUES ('flow',1,'a1b49edb-7636-416f-874a-88f94b859bef','2020-01-27 22:50:25')
```

**Comment by pawelpacana** [comment]
Errors from v.8.0:

```
Mysql2::Error: Duplicate entry 'a1b49edb-7636-416f-874a-88f94b859bef' for key 'event_store_events.PRIMARY': INSERT INTO `event_store_events` (`id`, `event_type`, `metadata`, `data`, `created_at`) VALUES ('a1b49edb-7636-416f-874a-88f94b859bef', 'SRecordTestEvent', x'7b7d', x'7b7d', '2020-01-27 22:53:12')
Mysql2::Error: Duplicate entry 'flow-a1b49edb-7636-416f-874a-88f94b859bef' for key 'event_store_events_in_streams.index_event_store_events_in_streams_on_stream_and_event_id': INSERT INTO `event_store_events_in_streams` (`stream`,`position`,`event_id`,`created_at`) VALUES ('flow',1,'a1b49edb-7636-416f-874a-88f94b859bef','2020-01-27 22:53:12')
```

**Comment by pawelpacana** [comment]
We now test on both MySQL 5 and 8. Nothing more to be done here.
