### ISSUE TITLE
In rails 5.1 migration throws exception

### ISSUE THREAD

**Issue by andriytyurnikov** [RailsEventStore/rails_event_store#70]
```
be rake db:migrate
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreateEventStoreEvents < ActiveRecord::Migration[4.2]
/Users/andriytyurnikov/Code/andriytyurnikov/blog_es_rails/db/migrate/20170713193136_create_event_store_events.rb:1:in `<top (required)>'
/Users/andriytyurnikov/.rbenv/versions/2.4.1/bin/bundle:22:in `load'
/Users/andriytyurnikov/.rbenv/versions/2.4.1/bin/bundle:22:in `<main>'
StandardError: Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreateEventStoreEvents < ActiveRecord::Migration[4.2]
/Users/andriytyurnikov/Code/andriytyurnikov/blog_es_rails/db/migrate/20170713193136_create_event_store_events.rb:1:in `<top (required)>'
/Users/andriytyurnikov/.rbenv/versions/2.4.1/bin/bundle:22:in `load'
/Users/andriytyurnikov/.rbenv/versions/2.4.1/bin/bundle:22:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by pawelpacana** [comment]
Hey @andriytyurnikov, thanks for reporting this problem! It has been fixed in recent release of https://github.com/RailsEventStore/rails_event_store_active_record/commit/9d2a94cdac0bbbae20d81ae68027b157a84e0aca which `rails_event_store` depends on.
